version: '1'
services:
  opdsulut:
    build: .
    working_dir: /src/app
    volumes:
      - .:/src/app
      - /node_modules
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    command: npm run dev